image: gitlab.ipb.uni-bonn.de:4567/ipb-team/global/docker-images/ipb_default

test:
  before_script:
  - pip3 install ruamel.yaml schema cpplint datetime
  script:
  - git submodule update --init
  - python3 -m unittest discover tests/
  tags:
  - docker
  except:
  - tags
